### ISSUE TITLE
typos in the beautiful website

### ISSUE THREAD

**Issue by melisandeteng** [cc-ai/art#1]
- mesmerazing --> mesmerizing
- Their heartbeats sooth the soul --> soothe
- When the center pixel is artifitially boosted --> artificially

**Comment by melisandeteng** [comment]
Also to 
"Stumbling upon your own failures can lift your spirits, when you are open to surprises.
A random collection of failures and accidents."

we could add "A random collection of failures and accidents when diving into depth maps."

**Comment by vict0rsch** [comment]
Done! Thanks for the catch, you could see how I typed carelessly :p
